version: '3.8'

services:
  jsonapi_app_spec:
    build: ./spec/jsonapi_app
    volumes:
      - ./spec/jsonapi_app:/jsonapi_app
      - /jsonapi_app/tmp/
    command: |
      bundle exec rails db:setup
      bundle exec rails s
    ports:
      - "3000:3000"
    environment:
      PGHOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"