version: '3.8'

networks:
  database:
    driver: bridge

services:
  app_database:
    image: postgres
    networks:
      database:
        aliases:
          - database
  spec:
    build: .
    entrypoint: bin/wait_for_it jsonapi_app_spec:3001 -t 30 --
    command: bundle exec rspec
    volumes:
      - .:/simple_jsonapi_client
    depends_on:
      - jsonapi_app_spec
    environment:
      API_URL: jsonapi_app_spec
      API_PORT: 3001
      PGHOST: app_database
    networks:
      - database
  jsonapi_app_spec:
    build: ./spec/jsonapi_app
    entrypoint: bin/wait_for_it app_database:5432 -t 30 --
    volumes:
      - ./spec/jsonapi_app:/jsonapi_app
      - /jsonapi_app/tmp/
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    ports:
      - "3001:3001"
    networks:
      - database
    environment:
      API_PORT: 3001
      PGHOST: app_database
    depends_on:
      - app_database
  console:
    build: .
    entrypoint: bin/wait_for_it jsonapi_app_console:3002 -t 30 --
    command: bin/development_start
    volumes:
      - .:/simple_jsonapi_client
    depends_on:
      - jsonapi_app_console
    environment:
      API_URL: jsonapi_app_console
      API_PORT: 3002
      PGHOST: app_database
    networks:
      - database
  jsonapi_app_console:
    build: ./spec/jsonapi_app
    entrypoint: bin/wait_for_it app_database:5432 -t 30 --
    volumes:
      - ./spec/jsonapi_app:/jsonapi_app
      - /jsonapi_app/tmp/
    command: bundle exec rails s -p 3002 -b '0.0.0.0'
    environment:
      PGHOST: app_database
    ports:
      - "3002:3002"
    networks:
      - database
    depends_on:
      - app_database
