version: '3.8'

services:
  jsonapi_app_spec:
    build: .
    entrypoint: /bin/sh -c "RAILS_ENV=development bundle exec rails db:setup && bundle exec rails s"
    volumes:
      - /jsonapi_app/tmp/
    command: /bin/sh -c "RAILS_ENV=development bin/rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      PGHOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"