version: '3.8'

services:
  jsonapi_app_spec:
    build: .
    container_name: jsonapi_app_spec
    entrypoint: /bin/sh -c "RAILS_ENV=development bin/rails s"
    volumes:
      - /jsonapi_app/tmp/
    ports:
      - "3000:3000"
    environment:
      PGHOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"