default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PGHOST"] || "localhost" %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: jsonapi_app_development

test:
  <<: *default
  database: jsonapi_app_test
