name: ci
on:
  push:

jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup project
        run: bin/setup

      - name: Run tests
        run: rake
