name: ci
on:
  push:

jobs:
  tests:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"

    env:
      PGUSER: postgres
      PGPASSWORD: postgres

    services:
      postgres:
        image: postgres:12-alpine
        ports: ["5432:5432"]
        env:
          PGDATA: "/var/lib/postgresql/data/pgdata"
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
        options: >-
          --tmpfs /var/lib/postgresql/data/pgdata
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Update PostgreSQL client
        run: |
          sudo apt install -y lsb-release
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
          sudo apt update
          sudo apt install postgresql-client-12
          
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup project
        run: bin/setup

      - name: Run tests
        run: rake
